### ISSUE TITLE
Cookies not permanently stored when using ORCA content

### ISSUE THREAD

**Issue by ckozianka** [orca-nrw/crossplatform-ilias-lti-plugin#19]
This happens outside of ILIAS when using ORCA content in a new window: In Chrome and Firefox cookies are stored but nonetheless one has to accept cookies on every new page of ORCA content.

**Comment by KaiOrca** [comment]
Issue is known - we will take care of this issue asap. Thank you again for letting us know

**Comment by ckozianka** [comment]
> Issue is known - we will take care of this issue asap. Thank you again for letting us know

This issue has obviously been fixed in the meantime. I'll close this issue.
